"""
Static metadata for all 17 PWD audit red flag rules.
Used for displaying rule library & enriching red flag records.
"""

RULES = [
    {
        "id": "R01",
        "code": "DIVERSION_OF_FUND",
        "title": "Diversion of fund across deposit works",
        "criteria": "The PW manual, para 305, provides that savings from one deposit work can be utilized in meeting other works only at the written request of the user department of the deposit works.",
        "source": "BEAMS MIS reports and extracted Cashbook from AMS",
        "detection": "If 'Remark' in Expenditure Details in utilization certificate is different from Name of Work, it indicates diversion of fund.",
        "severity": "critical",
        "parameter": "remark mismatch with work name",
        "applies_to": "deposit_work",
    },
    {
        "id": "R02",
        "code": "WASTEFUL_SURVEY",
        "title": "Wasteful expenditure on Survey works",
        "criteria": "As per tender conditions, survey of the work should be conducted properly before commencement.",
        "source": "BEAMS - PWD Capital Works Report",
        "detection": "If 'Remark' in Expenditure Details includes 'Survey Works' AND 'RA Bills' have Nil payment for other items.",
        "severity": "high",
        "parameter": "survey-only expenditure, no RA bill for other items",
        "applies_to": "capital_work",
    },
    {
        "id": "R03",
        "code": "EXCESS_WITHOUT_APPROVAL",
        "title": "Excess expenditure without government approval",
        "criteria": "Expenditure in excess of 10% of AA is required to be approved from Govt.",
        "source": "BEAMS - Utilisation Certificate",
        "detection": "If 'Up-to-date expenditure' exceeds AA Amount by more than 10%.",
        "severity": "critical",
        "parameter": "expenditure > 1.10 × AA Amount",
        "applies_to": "capital_work",
    },
    {
        "id": "R04",
        "code": "OVERLAPPING_MAINTENANCE",
        "title": "Overlapping works / avoidable DLP maintenance",
        "criteria": "Adequate planning should be ensured while awarding work orders for maintenance works.",
        "source": "BEAMS + Agreement Register",
        "detection": "Same MDR/SH/NH number with overlapping km chainage found in Annual Maintenance works during DLP period.",
        "severity": "high",
        "parameter": "same road code + overlapping km chainage",
        "applies_to": "capital_work",
    },
    {
        "id": "R05",
        "code": "DELAY_COMPLETION",
        "title": "Delay in completion of work",
        "criteria": "Work should be completed within the stipulated period.",
        "source": "BEAMS - Capital Works Report",
        "detection": "If Stipulated Date of Completion is earlier than today AND work is still in progress.",
        "severity": "medium",
        "parameter": "stipulated completion date < today",
        "applies_to": "capital_work",
    },
    {
        "id": "R06",
        "code": "SPLITTING_OF_WORK",
        "title": "Splitting of work to avoid tender process",
        "criteria": "Procurement up to 10 lakh via comparative rate list; above 10 lakh via e-tender.",
        "source": "Agreement Register",
        "detection": "Similar work with same road number and contiguous km awarded to same contractor in same year, each below ₹10 lakh.",
        "severity": "critical",
        "parameter": "same road + contiguous km + same contractor + same year + each <10 lakh",
        "applies_to": "agreement",
    },
    {
        "id": "R07",
        "code": "NO_CENTAGE_RECOVERY",
        "title": "Non-recovery of centage charges",
        "criteria": "MPW Manual & PWD instructions: centage charges at 5% of estimated cost of deposit works.",
        "source": "BEAMS - Deposit Works UC",
        "detection": "If 'Centage Amount' in Expenditure Details of Deposit UC is Nil but 'Bill Amount' is non-zero.",
        "severity": "high",
        "parameter": "centage_amount == 0 AND bill_amount > 0",
        "applies_to": "deposit_work",
    },
    {
        "id": "R08",
        "code": "UNSPENT_BALANCE",
        "title": "Unspent balance not returned to user department",
        "criteria": "Unspent deposits after completion of work should be returned to the user department.",
        "source": "BEAMS - Deposit Works UC",
        "detection": "If 'Balance Amount with DDO' > ₹1,00,000 AND Remark contains 'Work Completed'.",
        "severity": "high",
        "parameter": "balance > 100000 AND remark ~ 'Work Completed'",
        "applies_to": "deposit_work",
    },
    {
        "id": "R09",
        "code": "EXCESS_25_PERCENT",
        "title": "Excess expenditure beyond 25% of contract cost (Clause 38)",
        "criteria": "Clause 38: no rate revision if variation within 25% and excess value ≤ ₹5,000.",
        "source": "BEAMS UC - Expenditure Details",
        "detection": "Cumulative Expenditure exceeds Contract Cost by more than 25%.",
        "severity": "critical",
        "parameter": "cumulative_expenditure > 1.25 × contract_cost",
        "applies_to": "capital_work",
    },
    {
        "id": "R10",
        "code": "ABANDONED_WORK",
        "title": "Abandoned work (no progress >3 years)",
        "criteria": "If no progress in execution for last 2-3 years and work yet to be completed, decision for withdrawal or penalty is due.",
        "source": "BEAMS UC",
        "detection": "Cumulative Expenditure < 75% of Contract Cost AND last RA bill paid > 3 years ago.",
        "severity": "critical",
        "parameter": "cum_exp < 0.75 × contract_cost AND last_ra_bill > 3 yrs ago",
        "applies_to": "capital_work",
    },
    {
        "id": "R11",
        "code": "INFLATED_SSR",
        "title": "Inflated SSR/DSR (excessive below-10% tenders)",
        "criteria": "Para 150 MPW Manual: Estimates should be recast when accepted tender is below 10% of estimated cost.",
        "source": "Agreement Register",
        "detection": "If >20% of total yearly awards are below 10% tender OR if cost of below-tender works is >20% of total awarded cost.",
        "severity": "high",
        "parameter": "count% or cost% of below-10% works > 20%",
        "applies_to": "agreement",
    },
    {
        "id": "R12",
        "code": "PARKING_OF_FUND",
        "title": "Parking of fund (fag-end transfer)",
        "criteria": "Budget Manual: transfer of fund should not be used to park budget allocations.",
        "source": "BEAMS - Capital Works UC",
        "detection": "Payment > ₹50 lakh to another division in the month of March.",
        "severity": "critical",
        "parameter": "amount > 5000000 AND month == March AND transfer_to_other_division",
        "applies_to": "capital_work",
    },
    {
        "id": "R13",
        "code": "NO_DELAY_PENALTY",
        "title": "Non-imposition of penalties for delayed execution",
        "criteria": "Contractor liable to pay damages if work delayed beyond stipulated time as per agreement.",
        "source": "BEAMS",
        "detection": "Date of RA bill payment > Stipulated Completion Date (= Work Order Date + Time Limit).",
        "severity": "high",
        "parameter": "ra_bill_date > stipulated_completion_date",
        "applies_to": "capital_work",
    },
    {
        "id": "R14",
        "code": "INSURANCE_LAPSE",
        "title": "Non-renewal of Insurance Policy / Bank Guarantee",
        "criteria": "Tender conditions: Insurance Policy & BG must be submitted & renewed till completion.",
        "source": "BEAMS",
        "detection": "RA bill payment > stipulated completion date (indicates BG/Insurance likely lapsed).",
        "severity": "high",
        "parameter": "ra_bill_date > stipulated_completion_date",
        "applies_to": "capital_work",
    },
    {
        "id": "R15",
        "code": "SPLIT_HIGHER_SANCTION",
        "title": "Splitting of work to avoid higher-authority sanction",
        "criteria": "CE can accept tender > ₹2.5 cr up to ₹15 cr; >₹15 cr goes to Government.",
        "source": "BEAMS - Capital Works Report",
        "detection": "Similar works on adjacent lengths of same road with tech sanction cost > ₹1 cr each.",
        "severity": "critical",
        "parameter": "adjacent km on same road + tech_sanction > 10000000",
        "applies_to": "capital_work",
    },
    {
        "id": "R16",
        "code": "HAND_RECEIPT_PAYMENT",
        "title": "Irregular payment on Hand Receipt",
        "criteria": "MPW Manual: huge payment for regular work on Hand Receipt should generally be avoided.",
        "source": "AMS Cash Book (Form 10)",
        "detection": "Cash book shows payment > ₹10 lakh as 'paid vide Hand Receipt' / 'vide HR'.",
        "severity": "critical",
        "parameter": "amount > 1000000 AND payment_mode ~ 'Hand Receipt'",
        "applies_to": "cashbook",
    },
    {
        "id": "R17",
        "code": "NO_CLASSIFICATION",
        "title": "Irregular payment without proper classification",
        "criteria": "Huge cash-book payment with no Head of Accounts shown in classification column.",
        "source": "AMS Cash Book (Form 10)",
        "detection": "Payment > ₹10 lakh with empty Major Head / classification column.",
        "severity": "high",
        "parameter": "amount > 1000000 AND classification_head is empty",
        "applies_to": "cashbook",
    },
]

RULES_BY_ID = {r["id"]: r for r in RULES}
